// src/components/document/DocumentList.tsx
import { useState, useEffect, useCallback } from "react";
import { Table, Tag, Space, Modal, Dropdown, type MenuProps } from "antd";
import {
  FileOutlined,
  ExclamationCircleOutlined,
  UndoOutlined,
  DeleteOutlined,
  PaperClipOutlined,
  FolderOpenOutlined,
} from "@ant-design/icons";
import { open } from "@tauri-apps/plugin-dialog";
import { WebviewWindow } from "@tauri-apps/api/webviewWindow";
import type { ColumnsType } from "antd/es/table";
import { useI18n } from "../../lib/i18n";
import { useAppStore } from "../../stores/useAppStore";

import DocumentToolbar from "./DocumentToolbar";

// Lazy load invoke helper - works in both Tauri and browser
async function invokeCommand<T = unknown>(
  cmd: string,
  args?: Record<string, unknown>,
): Promise<T> {
  const { invoke } = await import("@tauri-apps/api/core");
  return invoke<T>(cmd, args);
}

// Predefined color palette for tags
const TAG_COLORS: Record<string, string> = {
  red: "#ef4444",
  orange: "#f97316",
  amber: "#f59e0b",
  yellow: "#eab308",
  lime: "#84cc16",
  green: "#22c55e",
  emerald: "#10b981",
  teal: "#14b8a6",
  cyan: "#06b6d4",
  sky: "#0ea5e9",
  blue: "#3b82f6",
  indigo: "#6366f1",
  violet: "#8b5cf6",
  purple: "#a855f7",
  fuchsia: "#d946ef",
  pink: "#ec4899",
  rose: "#f43f5e",
};

interface LabelDto {
  id: number;
  name: string;
  color: string;
}

interface AttachmentDto {
  id: number;
  paper_id: number;
  file_name: string;
  file_type: string;
  created_at: string;
}

interface PaperDto {
  id: number;
  title: string;
  publication_year?: number;
  journal_name?: string;
  conference_name?: string;
  authors: string[];
  labels: LabelDto[];
  attachment_count?: number;
}

interface DocumentListProps {
  onDocumentSelect: (document: any) => void;
  categoryId?: string | null;
}

const AttachmentList = ({ paperId }: { paperId: number }) => {
  const [attachments, setAttachments] = useState<AttachmentDto[]>([]);
  const [loading, setLoading] = useState(true);

  const loadAttachments = useCallback(async () => {
    setLoading(true);
    try {
      const data = await invokeCommand<AttachmentDto[]>("get_attachments", {
        paperId: paperId,
      });
      setAttachments(data);
    } catch (error) {
      console.error("Failed to load attachments:", error);
    } finally {
      setLoading(false);
    }
  }, [paperId]);

  useEffect(() => {
    loadAttachments();

    const handleUpdate = (e: Event) => {
      const detail = (e as CustomEvent).detail;
      if (detail && detail.paperId === paperId) {
        loadAttachments();
      }
    };

    window.addEventListener("attachment-updated", handleUpdate);
    return () => window.removeEventListener("attachment-updated", handleUpdate);
  }, [loadAttachments, paperId]);

  if (loading) return <div style={{ padding: "8px 0" }}>Loading...</div>;
  if (attachments.length === 0)
    return (
      <div style={{ color: "#999", padding: "8px 0" }}>No attachments</div>
    );

  return (
    <div style={{ padding: "8px 0" }}>
      <Space direction="vertical" style={{ width: "100%" }}>
        {attachments.map((att) => (
          <div
            key={att.id}
            style={{
              display: "flex",
              alignItems: "center",
              gap: "8px",
              padding: "4px 8px",
              backgroundColor: "#f5f5f5",
              borderRadius: "4px",
            }}
          >
            <FileOutlined />
            <span style={{ flex: 1 }}>{att.file_name}</span>
            <span style={{ color: "#999", fontSize: "12px" }}>
              {new Date(att.created_at).toLocaleDateString()}
            </span>
          </div>
        ))}
      </Space>
    </div>
  );
};

export default function DocumentList({
  onDocumentSelect,
  categoryId,
}: DocumentListProps) {
  const { t } = useI18n();
  const { selectedDocument, accentColor } = useAppStore();
  const [rows, setRows] = useState<PaperDto[]>([]);
  const [loading, setLoading] = useState(true);

  const loadPapers = useCallback(async () => {
    setLoading(true);
    try {
      let papers: PaperDto[];
      if (categoryId === "trash") {
        papers = await invokeCommand<PaperDto[]>("get_deleted_papers");
      } else if (categoryId) {
        // Load papers for specific category
        papers = await invokeCommand<PaperDto[]>("get_papers_by_category", {
          categoryPath: categoryId,
        });
      } else {
        // Load all papers
        papers = await invokeCommand<PaperDto[]>("get_all_papers");
      }
      setRows(papers);
      if (papers.length > 0) {
        onDocumentSelect(papers[0]);
      }
    } catch (error) {
      console.error("Failed to load papers:", error);
      // Demo data if backend fails (dev mode without tauri)
      const demoData = [
        {
          id: 1,
          title: "Attention Is All You Need",
          authors: ["Vaswani et al."],
          publication_year: 2017,
          conference_name: "NIPS",
          labels: [],
        },
      ];
      setRows(demoData);
      if (demoData.length > 0) {
        onDocumentSelect(demoData[0]);
      }
    } finally {
      setLoading(false);
    }
  }, [categoryId, onDocumentSelect]);

  useEffect(() => {
    loadPapers();

    const handlePaperUpdate = (e: Event) => {
      const detail = (e as CustomEvent).detail as PaperDto;
      setRows((prev) =>
        prev.map((row) => (row.id === detail.id ? { ...row, ...detail } : row)),
      );
    };

    window.addEventListener("paper-updated", handlePaperUpdate);
    return () => window.removeEventListener("paper-updated", handlePaperUpdate);
  }, [loadPapers]);

  const handleDoubleClick = useCallback(async (record: PaperDto) => {
    console.info("Double clicked paper:", record.id, record.title);
    // Check if paper has PDF attachments
    if ((record.attachment_count || 0) > 0) {
      try {
        // Create a new window for PDF viewer
        const label = `pdf-viewer-${record.id}`;
        const webview = new WebviewWindow(label, {
          url: `http://localhost:1420/src/pdf-viewer.html`,
          title: record.title,
          width: 1000,
          height: 800,
          resizable: true,
          center: true,
          decorations: true,
          focus: true,
        });

        // Listen for creation errors
        webview.once("tauri://error", (e) => {
          console.error("Failed to create PDF viewer window:", e);
          Modal.error({
            title: "Failed to open PDF viewer",
            content: `Could not open PDF viewer window: ${e.payload}`,
          });
        });

        console.info(`Opening PDF viewer window for paper ${record.id}`);
      } catch (err) {
        console.error("Failed to open PDF viewer window:", err);
        Modal.error({
          title: "Failed to open PDF viewer",
          content: "Could not open PDF viewer window. Please try again.",
        });
      }
    } else {
      Modal.info({
        title: "No PDF attachment",
        content:
          "This paper has no PDF attachment. Please add a PDF file first.",
      });
    }
  }, []);

  const handleRowClick = useCallback(
    (record: PaperDto) => {
      onDocumentSelect(record);
    },
    [onDocumentSelect],
  );

  const columns: ColumnsType<PaperDto> = [
    {
      title: t("document.title"),
      dataIndex: "title",
      key: "title",
      ellipsis: true,
      width: 250,
    },
    {
      title: t("document.authors"),
      dataIndex: "authors",
      key: "authors",
      ellipsis: true,
      width: 200,
      render: (authors: string[]) => (
        <div style={{ overflow: "hidden", whiteSpace: "nowrap" }}>
          <Space size="small" style={{ flexWrap: "nowrap" }}>
            {authors?.map((author, index) => (
              <Tag key={index}>{author}</Tag>
            ))}
          </Space>
        </div>
      ),
    },
    {
      title: t("document.source"),
      dataIndex: "source",
      key: "source",
      ellipsis: true,
      width: 150,
      render: (_value, record: PaperDto) =>
        record.journal_name || record.conference_name || "",
    },
    {
      title: t("document.year"),
      dataIndex: "publication_year",
      key: "publication_year",
      ellipsis: true,
      width: 80,
    },
    {
      title: t("document.labels"),
      dataIndex: "labels",
      key: "labels",
      ellipsis: true,
      width: 320,
      render: (labels: LabelDto[]) => (
        <div style={{ overflow: "hidden", whiteSpace: "nowrap" }}>
          <Space size="small" style={{ flexWrap: "nowrap" }}>
            {labels?.map((label) => (
              <Tag
                key={label.id}
                style={{
                  backgroundColor: TAG_COLORS[label.color] || TAG_COLORS.blue,
                  color: "#fff",
                  maxWidth: "100px",
                  overflow: "hidden",
                  textOverflow: "ellipsis",
                  verticalAlign: "top",
                }}
              >
                {label.name}
              </Tag>
            ))}
          </Space>
        </div>
      ),
    },
  ];

  const TableRow = useCallback(
    ({ children, ...props }: any) => {
      const rowId = props["data-row-key"];
      let menuItems: MenuProps["items"] = [];

      if (categoryId === "trash") {
        menuItems = [
          {
            key: "restore",
            label: t("dialog.restore"),
            icon: <UndoOutlined />,
            onClick: async () => {
              try {
                await invokeCommand("restore_paper", { id: rowId });
                await loadPapers();
              } catch (error) {
                console.error("Failed to restore paper:", error);
                Modal.error({
                  title: t("dialog.restoreFailed"),
                  content: String(error),
                });
              }
            },
          },
          {
            key: "permanently_delete",
            label: t("dialog.permanentlyDelete"),
            icon: <DeleteOutlined />,
            danger: true,
            onClick: () => {
              Modal.confirm({
                title: t("dialog.permanentlyDelete"),
                icon: <ExclamationCircleOutlined />,
                content: t("dialog.confirmPermanentlyDelete"),
                okText: t("dialog.permanentlyDelete"),
                okType: "danger",
                cancelText: t("dialog.cancel"),
                onOk: async () => {
                  try {
                    await invokeCommand("permanently_delete_paper", {
                      id: rowId,
                    });
                    await loadPapers();
                  } catch (error) {
                    console.error("Failed to delete paper:", error);
                    Modal.error({
                      title: t("dialog.deleteFailed"),
                      content: String(error),
                    });
                  }
                },
              });
            },
          },
        ];
      } else {
        menuItems = [
          {
            key: "add_attachment",
            label: "添加附件",
            icon: <PaperClipOutlined />,
            onClick: async () => {
              try {
                const selected = await open({
                  multiple: false,
                  directory: false,
                });
                if (selected) {
                  const filePath = Array.isArray(selected)
                    ? selected[0]
                    : selected;
                  if (filePath) {
                    await invokeCommand("add_attachment", {
                      paperId: rowId,
                      filePath: filePath,
                    });
                    window.dispatchEvent(
                      new CustomEvent("attachment-updated", {
                        detail: { paperId: rowId },
                      }),
                    );
                    await loadPapers();
                    Modal.success({ content: "Attachment added successfully" });
                  }
                }
              } catch (error) {
                console.error("Failed to add attachment:", error);
                Modal.error({
                  title: "Failed to add attachment",
                  content: String(error),
                });
              }
            },
          },
          {
            key: "open_folder",
            label: "打开附件文件夹",
            icon: <FolderOpenOutlined />,
            onClick: async () => {
              try {
                await invokeCommand("open_paper_folder", { paperId: rowId });
              } catch (error) {
                console.error("Failed to open folder:", error);
                Modal.error({
                  title: "Failed to open folder",
                  content: String(error),
                });
              }
            },
          },
          {
            type: "divider",
          },
          {
            key: "delete",
            label: t("dialog.delete"),
            danger: true,
            icon: <DeleteOutlined />,
            onClick: () => {
              Modal.confirm({
                title: t("dialog.delete"),
                icon: <ExclamationCircleOutlined />,
                content: "确定要删除此文档吗？此操作将把文档移入回收站。",
                okText: t("dialog.delete"),
                okType: "danger",
                cancelText: t("dialog.cancel"),
                onOk: async () => {
                  try {
                    await invokeCommand("delete_paper", { id: rowId });
                    await loadPapers();
                  } catch (error) {
                    console.error("Failed to delete paper:", error);
                    Modal.error({
                      title: t("dialog.deleteFailed"),
                      content: String(error),
                    });
                  }
                },
              });
            },
          },
        ];
      }

      return (
        <Dropdown menu={{ items: menuItems }} trigger={["contextMenu"]}>
          <tr {...props}>{children}</tr>
        </Dropdown>
      );
    },
    [t, categoryId, loadPapers],
  );

  return (
    <div
      style={{
        height: "100%",
        width: "100%",
        display: "flex",
        flexDirection: "column",
        overflow: "hidden",
      }}
    >
      {/* Toolbar */}
      <DocumentToolbar onRefresh={loadPapers} selectedCategoryId={categoryId} />

      {/* Table Container */}
      <div
        style={{
          flex: 1,
          overflow: "auto",
          minHeight: 0,
        }}
      >
        <Table
          components={{
            body: {
              row: TableRow,
            },
          }}
          dataSource={rows}
          columns={columns}
          loading={loading}
          rowKey="id"
          size="small"
          pagination={false}
          expandable={{
            expandedRowRender: (record) => (
              <div style={{ marginLeft: "50px" }}>
                <AttachmentList paperId={record.id} />
              </div>
            ),
            rowExpandable: (record) => (record.attachment_count || 0) > 0,
            expandIcon: ({ expanded, onExpand, record }) =>
              (record.attachment_count || 0) > 0 ? (
                <FileOutlined
                  onClick={(e) => onExpand(record, e)}
                  style={{
                    cursor: "pointer",
                    marginRight: 8,
                    color: expanded ? accentColor : undefined,
                  }}
                />
              ) : null,
          }}
          onRow={(record) => {
            const isSelected = selectedDocument?.id === record.id;
            return {
              onClick: () => {
                console.info("Row clicked", record.id);
                handleRowClick(record);
              },
              onDoubleClick: () => {
                console.info("Row double clicked", record.id);
                handleDoubleClick(record);
              },
              style: {
                cursor: "pointer",
                backgroundColor: isSelected ? `${accentColor}40` : undefined,
                userSelect: "none",
              },
            };
          }}
        />
      </div>
    </div>
  );
}

// src/components/document/DocumentList.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, reactive } from "vue";
import { useRouter } from "vue-router";
import { invokeCommand } from "@/lib/tauri";
import type { VxeTablePropTypes } from "vxe-table";
import DocumentToolbar from "./DocumentToolbar.vue";
import { useI18n } from "@/lib/i18n";
import { open } from "@tauri-apps/plugin-dialog";
import { getCurrentWindow } from "@tauri-apps/api/window";
import { WebviewWindow } from "@tauri-apps/api/webviewWindow";

const { t } = useI18n();
const router = useRouter();

interface Label {
  id: number;
  name: string;
  color: string;
}

interface Attachment {
  id: number;
  paper_id: number;
  file_name: string | null;
  file_type: string | null;
  created_at: string | null;
}

interface PaperDto {
  id: number;
  title: string;
  authors: string[];
  publication_year?: number;
  journal_name?: string;
  labels: Label[];
  attachment_count?: number;
  attachments?: Attachment[];
}

interface Props {
  categoryId?: number | null;
  currentView?: "library" | "favorites" | "trash";
}

const props = withDefaults(defineProps<Props>(), {
  categoryId: null,
  currentView: "library",
});

const emit = defineEmits<{
  paperSelect: [paperId: number];
  paperUpdated: [paperId: number, detail: PaperDetail];
}>();

// State
const loading = ref(false);
const papers = ref<PaperDto[]>([]);

// Table ref

// Expand configuration
const expandRowIds = ref<number[]>([]);

const expandConfig = computed<VxeTablePropTypes.ExpandConfig>(() => ({
  showIcon: true,
  trigger: "row",
  expandRowKeys: expandRowIds.value,
  accordion: true, // 手风琴模式：展开一行时其他行自动折叠
  visibleMethod: ({ row }) => {
    // 只对有附件的行显示展开图标
    return ((row as PaperDto).attachment_count ?? 0) > 0;
  },
  toggleMethod({ expanded, row }) {
    const paper = row as PaperDto;
    if (expanded) {
      if ((paper.attachment_count ?? 0) === 0) {
        return false; // 没有附件，禁止展开
      }
      return true;
    } else {
      if ((paper.attachment_count ?? 0) === 0) {
        return false; // 没有附件，禁止展开
      }
      return true; // 有附件，允许展开
    }
  },
}));

// Sort configuration
const sortConfig = reactive({
  defaultSort: {
    field: "" as string,
    order: "" as "asc" | "desc",
  },
});

// Context menu configuration
const contextMenuConfig = computed(() => {
  // Build menu items based on current view (must be 2D array)
  if (props.currentView === "trash") {
    // Trash view menu
    return {
      body: {
        options: [
          [
            {
              code: "restore",
              name: t("dialog.restore"),
              prefixConfig: { icon: "vxe-icon-undo" },
            },
            {
              code: "permanently_delete",
              name: t("dialog.permanentlyDelete"),
              prefixConfig: { icon: "vxe-icon-delete" },
            },
          ],
        ],
      },
    };
  } else {
    // Normal view menu
    return {
      body: {
        options: [
          [
            {
              code: "add_attachment",
              name: "添加附件",
              prefixConfig: { icon: "vxe-icon-file" },
            },
            {
              code: "open_folder",
              name: "打开附件文件夹",
              prefixConfig: { icon: "vxe-icon-folder-open" },
            },
          ],
          [
            {
              code: "delete",
              name: t("dialog.delete"),
              prefixConfig: { icon: "vxe-icon-folder-open" },
            },
          ],
        ],
      },
    };
  }
});

// Handle context menu click
async function handleContextMenuClick({ menu, row }: any) {
  const paper = row as PaperDto;
  console.info("Context menu clicked:", menu.code, paper);

  switch (menu.code) {
    case "add_attachment":
      await handleAddAttachment(paper);
      break;
    case "open_folder":
      await handleOpenFolder(paper);
      break;
    case "delete":
      await handleDeletePaper(paper);
      break;
    case "restore":
      await handleRestorePaper(paper);
      break;
    case "permanently_delete":
      await handlePermanentlyDeletePaper(paper);
      break;
  }
}

// Handle context menu shown (for debugging)
function handleContextMenuVisible({ type, row, column }: any) {
  console.info("Context menu shown:", { type, row, column });
}

// Add attachment to paper
async function handleAddAttachment(paper: PaperDto) {
  try {
    const selected = await open({
      multiple: false,
      directory: false,
    });
    if (selected) {
      const filePath = Array.isArray(selected) ? selected[0] : selected;
      if (filePath) {
        await invokeCommand("add_attachment", {
          paperId: paper.id,
          filePath: filePath,
        });
        // Reload papers to show updated attachment count
        await loadPapers();
        console.info("Attachment added successfully");
      }
    }
  } catch (error) {
    console.error("Failed to add attachment:", error);
  }
}

// Open paper folder
async function handleOpenFolder(paper: PaperDto) {
  try {
    await invokeCommand("open_paper_folder", { paperId: paper.id });
  } catch (error) {
    console.error("Failed to open folder:", error);
  }
}

// Delete paper (move to trash)
async function handleDeletePaper(paper: PaperDto) {
  try {
    await invokeCommand("delete_paper", { id: paper.id });
    await loadPapers();
  } catch (error) {
    console.error("Failed to delete paper:", error);
  }
}

// Restore paper from trash
async function handleRestorePaper(paper: PaperDto) {
  try {
    await invokeCommand("restore_paper", { id: paper.id });
    await loadPapers();
  } catch (error) {
    console.error("Failed to restore paper:", error);
  }
}

// Permanently delete paper
async function handlePermanentlyDeletePaper(paper: PaperDto) {
  try {
    await invokeCommand("permanently_delete_paper", { id: paper.id });
    await loadPapers();
  } catch (error) {
    console.error("Failed to permanently delete paper:", error);
  }
}

// Table columns definition

// Load papers from backend based on current view
async function loadPapers() {
  loading.value = true;
  try {
    let data: PaperDto[];

    if (props.currentView === "trash") {
      // Load deleted papers
      data = await invokeCommand<PaperDto[]>("get_deleted_papers");
    } else if (props.categoryId) {
      // Load papers for specific category
      data = await invokeCommand<PaperDto[]>("get_papers_by_category", {
        categoryId: props.categoryId,
      });
    } else {
      // Load all papers (library view)
      data = await invokeCommand<PaperDto[]>("get_all_papers");
    }

    papers.value = data;
  } catch (error) {
    console.error("Failed to load papers:", error);
  } finally {
    loading.value = false;
  }
}

// // Handle row click - emit paper selection
// function handleCellClick({ row }: { row: PaperDto }) {
//   emit("paperSelect", row.id);
// }

// // Handle row double click - navigate to paper detail
// function handleRowDblclick({ row }: { row: PaperDto }) {
//   router.push(`/papers/${row.id}`);
// }

// Handle sort change
function handleSortChange(params: any) {
  const { sortList } = params;
  if (sortList && sortList.length > 0) {
    const { field, order } = sortList[0];
    sortConfig.defaultSort.field = field;
    sortConfig.defaultSort.order = order as "asc" | "desc";

    // Sort papers locally
    papers.value.sort((a, b) => {
      const aVal = (a as any)[field];
      const bVal = (b as any)[field];

      if (aVal === undefined || aVal === null) return 1;
      if (bVal === undefined || bVal === null) return -1;
      if (aVal < bVal) return order === "asc" ? -1 : 1;
      if (aVal > bVal) return order === "asc" ? 1 : -1;
      return 0;
    });
  }
}

// Handle cell click event
function cellClickEvent({ row, column }: { row: any; column: any }) {
  console.log(`Single clicked row: ${row.id}, column: ${column.field}`);
  emit("paperSelect", row.id);
}

// Handle cell double click event
async function cellDblclickEvent({ row, column }: { row: any; column: any }) {
  console.log(`Double clicked row: ${row.id}, column: ${column.field}`);

  const paper = row as PaperDto;

  // Check if paper has attachments
  if ((paper.attachment_count ?? 0) === 0) {
    console.info(`Paper ${paper.id} has no attachments`);
    return;
  }

  try {
    // Create PDF viewer window with unique label
    const windowLabel = `pdf-viewer-${paper.id}`;

    // Check if PDF viewer window already exists
    const existingPdfWindow = await WebviewWindow.getByLabel(windowLabel);

    if (existingPdfWindow) {
      // Focus existing window instead of creating a new one
      await existingPdfWindow.setFocus();
      await existingPdfWindow.unminimize();
      console.info(`Focused existing PDF viewer window for paper ${paper.id}`);
      return;
    }

    // Create new PDF viewer window
    const webview = new WebviewWindow(windowLabel, {
      title: paper.title,
      url: "/pdf-viewer.html",
      width: 1200,
      height: 800,
      center: true,
      resizable: true,
      decorations: true,
      transparent: false,
      alwaysOnTop: false,
    });

    // Wait for window to be created
    webview.once("tauri://created", async () => {
      console.info(`PDF viewer window created for paper ${paper.id}`);
      await webview.show();
      await webview.setFocus();
    });

    webview.once("tauri://error", (error) => {
      console.error("Failed to create PDF viewer window:", error);
    });
  } catch (error) {
    console.error("Failed to open PDF viewer:", error);
  }
}

// Handle expand row toggle
function handleToggleExpandChange({ row }: { row: any }) {
  const index = expandRowIds.value.indexOf(row.id);

  console.info(
    "Toggle expand clicked for row:",
    row.id,
    "current expanded rows:",
    expandRowIds.value,
  );

  if (index > -1) {
    // Collapse
    expandRowIds.value.splice(index, 1);
    console.info("Collapsed row:", row.id);
  } else {
    // Expand - attachments are already loaded from backend
    expandRowIds.value.push(row.id);
    console.info(
      "Expanded row:",
      row.id,
      "attachment_count:",
      row.attachment_count,
      "attachments:",
      row.attachments?.length || 0,
    );
  }
}

// Handle expand row change event (fallback)

// Check if row is expanded

// Get file icon based on file type
function getFileIcon(fileType: string | null): string {
  if (!fileType) return "mdi-file";
  const type = fileType.toLowerCase();
  if (type.includes("pdf")) return "mdi-file-pdf-box";
  if (type.includes("doc") || type.includes("word")) return "mdi-file-word-box";
  if (
    type.includes("xls") ||
    type.includes("excel") ||
    type.includes("spreadsheet")
  )
    return "mdi-file-excel-box";
  if (type.includes("ppt") || type.includes("powerpoint"))
    return "mdi-file-powerpoint-box";
  if (type.includes("txt")) return "mdi-file-document-box";
  if (type.includes("zip") || type.includes("rar") || type.includes("archive"))
    return "mdi-file-zip-box";
  return "mdi-file";
}

// Watch category ID changes
watch(
  () => props.categoryId,
  () => {
    loadPapers();
  },
);

// Watch current view changes
watch(
  () => props.currentView,
  () => {
    // Clear expanded rows when view changes
    expandRowIds.value = [];
    loadPapers();
  },
);

// Load on mount
onMounted(() => {
  loadPapers();
});

// Expose load function for parent component refresh
defineExpose({
  loadPapers,
});
</script>

<template>
  <div class="document-list">
    <!-- View indicator -->
    <div v-if="currentView === 'trash'" class="view-indicator">
      <v-icon size="small" color="warning" class="mr-2">mdi-delete</v-icon>
      <span class="text-caption">{{ $t("navigation.trash") }}</span>
    </div>

    <!-- Toolbar -->
    <DocumentToolbar
      :on-refresh="loadPapers"
      :selected-category-id="categoryId"
    />

    <div class="table-container">
      <!-- Loading overlay -->
      <div v-if="loading" class="loading-overlay">
        <v-progress-circular indeterminate size="48" />
      </div>

      <vxe-table
        ref="tableRef"
        :data="papers"
        :expand-config="expandConfig"
        :column-config="{ resizable: true }"
        :menu-config="contextMenuConfig"
        :sort-config="{
          trigger: 'cell',
          defaultSort: sortConfig.defaultSort.field
            ? {
                field: sortConfig.defaultSort.field,
                order: sortConfig.defaultSort.order,
              }
            : undefined,
        }"
        :row-config="{ isCurrent: true, isHover: true, keyField: 'id' }"
        :cell-config="{ height: 32 }"
        :style="{
          '--vxe-ui-table-row-current-background-color':
            'rgba(var(--v-theme-primary), 0.2)',
          '--vxe-ui-table-row-hover-current-background-color':
            'rgba(var(--v-theme-primary), 0.3)',
        }"
        height="100%"
        stripe
        border
        size="mini"
        @cell-click="cellClickEvent"
        @cell-dblclick="cellDblclickEvent"
        @sort-change="handleSortChange"
        @toggle-expand-change="handleToggleExpandChange"
        @menu-click="handleContextMenuClick"
        @menu-visible="handleContextMenuVisible"
      >
        <!-- Expand column (only for papers with attachments) -->
        <vxe-column type="expand" width="40" fixed="left">
          <template #content="{ row }">
            <div class="expand-row-content">
              <div
                v-if="row.attachments && row.attachments.length > 0"
                class="attachments-list"
              >
                <div class="attachments-header">
                  <v-icon size="small" class="mr-2">mdi-paperclip</v-icon>
                  <span class="text-subtitle-2"
                    >Attachments ({{ row.attachments.length }})</span
                  >
                </div>
                <v-list density="compact" class="attachments-list-items">
                  <v-list-item
                    v-for="attachment in row.attachments"
                    :key="attachment.id"
                    class="attachment-item"
                  >
                    <template #prepend>
                      <v-icon
                        :icon="getFileIcon(attachment.file_type)"
                        size="small"
                      />
                    </template>
                    <v-list-item-title>
                      {{ attachment.file_name || "Unnamed file" }}
                    </v-list-item-title>
                    <v-list-item-subtitle v-if="attachment.file_type">
                      {{ attachment.file_type }}
                      <span v-if="attachment.created_at">
                        •
                        {{
                          new Date(attachment.created_at).toLocaleDateString()
                        }}
                      </span>
                    </v-list-item-subtitle>
                  </v-list-item>
                </v-list>
              </div>
              <div v-else class="no-attachments">
                <v-icon size="small" class="mr-2">mdi-information</v-icon>
                <span class="text-caption">No attachments</span>
              </div>
            </div>
          </template>
        </vxe-column>

        <!-- Title column -->
        <vxe-column
          field="title"
          title="Title"
          min-width="200"
          sortable
          show-overflow
        >
          <template #default="{ row }">
            <span class="text-truncate">{{ row.title }}</span>
          </template>
        </vxe-column>

        <!-- Authors column -->
        <vxe-column field="authors" title="Authors" width="15%" show-overflow>
          <template #default="{ row }">
            <v-chip
              v-if="row.authors && row.authors.length > 0"
              size="x-small"
              class="mr-1"
            >
              {{ row.authors[0] }}
            </v-chip>
            <v-chip v-if="row.authors && row.authors.length > 1" size="x-small">
              +{{ row.authors.length - 1 }}
            </v-chip>
          </template>
        </vxe-column>

        <!-- Year column -->
        <vxe-column field="publication_year" title="Year" width="80" sortable />

        <!-- Journal column -->
        <vxe-column
          field="journal_name"
          title="Journal"
          width="20%"
          sortable
          show-overflow
        />

        <!-- Labels column -->
        <vxe-column field="labels" title="Labels" width="15%" show-overflow>
          <template #default="{ row }">
            <v-chip
              v-if="row.labels && row.labels.length > 0"
              size="x-small"
              :color="row.labels[0].color"
              class="mr-1"
            >
              {{ row.labels[0].name }}
            </v-chip>
            <v-chip v-if="row.labels && row.labels.length > 1" size="x-small">
              +{{ row.labels.length - 1 }}
            </v-chip>
          </template>
        </vxe-column>
      </vxe-table>
    </div>
  </div>
</template>

<style scoped>
.document-list {
  height: 100%;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.view-indicator {
  display: flex;
  align-items: center;
  padding: 8px 16px;
  background-color: rgba(255, 152, 0, 0.1);
  border-bottom: 1px solid rgba(255, 255, 255, 0.12);
  flex-shrink: 0;
}

.table-container {
  flex: 1;
  overflow: hidden;
  position: relative;
}

.loading-overlay {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: rgba(0, 0, 0, 0.5);
  z-index: 100;
}

.text-truncate {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

:deep(.vxe-table) {
  background-color: transparent;
}

:deep(.vxe-table--body .vxe-body--row.row--checked) {
  background-color: rgba(var(--v-theme-primary), 0.1);
}

:deep(.vxe-table--body .vxe-body--row:hover) {
  cursor: pointer;
}

:deep(.vxe-table .vxe-body--column) {
  padding: 4px 8px;
}

:deep(.vxe-table .vxe-header--column) {
  padding: 6px 8px;
  font-weight: 600;
  font-size: 13px;
}

:deep(.vxe-table--render-default .vxe-body--column) {
  font-size: 13px;
}

:deep(.vxe-table--render-default.size--mini .vxe-body--column) {
  padding: 2px 8px;
}

:deep(.vxe-table--render-default.size--mini .vxe-header--column) {
  padding: 4px 8px;
  font-size: 12px;
}

/* Expand row styles */
.expand-row-content {
  padding: 12px 16px;
  background-color: var(--vxe-table-body-background-color);
}

.attachments-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.attachments-header {
  display: flex;
  align-items: center;
  font-weight: 600;
  padding-bottom: 8px;
  border-bottom: 1px solid rgba(255, 255, 255, 0.12);
}

.attachments-list-items {
  background-color: transparent;
  padding: 0;
}

.attachment-item {
  padding: 4px 8px;
  min-height: auto;
}

.attachment-item :deep(.v-list-item-title) {
  font-size: 13px;
}

.attachment-item :deep(.v-list-item-subtitle) {
  font-size: 11px;
  opacity: 0.7;
}

.no-attachments {
  display: flex;
  align-items: center;
  opacity: 0.6;
  font-style: italic;
}

/* Expand icon rotation */
.rotate-90 {
  transform: rotate(90deg);
}

/* Expand row styling */
:deep(.vxe-table--expand-icon) {
  transition: transform 0.2s ease;
}

:deep(.vxe-body--row.row--expanded .vxe-body--expand-row) {
  background-color: var(--vxe-table-body-background-color);
}

/* Disable text selection on double click */
:deep(.vxe-table) {
  user-select: none;
  -webkit-user-select: none;
}

:deep(.vxe-table .vxe-body--column) {
  user-select: text;
  -webkit-user-select: text;
}
</style>
