// src/components/document/DocumentToolbar.vue
<script setup lang="ts">
import { ref } from "vue";
import { invokeCommand } from "@/lib/tauri";
import { open } from "@tauri-apps/plugin-dialog";
import { useI18n } from "@/lib/i18n";

interface Props {
  onRefresh?: () => void;
  selectedCategoryId?: number | null;
}

const props = withDefaults(defineProps<Props>(), {
  onRefresh: undefined,
  selectedCategoryId: null,
});

const { t } = useI18n();

// Dialog states
const doiDialogOpen = ref(false);
const doiInput = ref("");
const doiLoading = ref(false);
const doiError = ref("");

const arxivDialogOpen = ref(false);
const arxivInput = ref("");
const arxivLoading = ref(false);
const arxivError = ref("");

// DOI import handlers
function handleDoiButtonClick() {
  doiDialogOpen.value = true;
  doiInput.value = "";
  doiError.value = "";
}

function handleDoiDialogClose() {
  doiDialogOpen.value = false;
  doiInput.value = "";
  doiError.value = "";
}

async function handleDoiSubmit() {
  const trimmed = doiInput.value.trim();
  if (!trimmed) {
    doiError.value = t("toolbar.doiRequired");
    return;
  }

  doiLoading.value = true;
  doiError.value = "";

  try {
    await invokeCommand("import_paper_by_doi", {
      doi: trimmed,
      categoryId: props.selectedCategoryId,
    });

    // Refresh the document list
    if (props.onRefresh) {
      await props.onRefresh();
    }

    handleDoiDialogClose();
  } catch (error) {
    console.error("Failed to import paper by DOI:", error);
    doiError.value = String(error);
  } finally {
    doiLoading.value = false;
  }
}

// arXiv import handlers
function handleArxivButtonClick() {
  arxivDialogOpen.value = true;
  arxivInput.value = "";
  arxivError.value = "";
}

function handleArxivDialogClose() {
  arxivDialogOpen.value = false;
  arxivInput.value = "";
  arxivError.value = "";
}

async function handleArxivSubmit() {
  const trimmed = arxivInput.value.trim();
  if (!trimmed) {
    arxivError.value = t("toolbar.arxivRequired");
    return;
  }

  arxivLoading.value = true;
  arxivError.value = "";

  try {
    await invokeCommand("import_paper_by_arxiv_id", {
      arxivId: trimmed,
      categoryId: props.selectedCategoryId,
    });

    // Refresh the document list
    if (props.onRefresh) {
      await props.onRefresh();
    }

    handleArxivDialogClose();
  } catch (error) {
    console.error("Failed to import paper by arXiv ID:", error);
    arxivError.value = String(error);
  } finally {
    arxivLoading.value = false;
  }
}

// PDF import handler
async function handlePdfImport() {
  try {
    const selected = await open({
      multiple: false,
      directory: false,
      filters: [{ name: "PDF", extensions: ["pdf"] }],
    });

    if (selected) {
      const filePath = Array.isArray(selected) ? selected[0] : selected;
      if (filePath) {
        try {
          await invokeCommand("import_paper_by_pdf", {
            filePath: filePath,
            categoryId: props.selectedCategoryId,
          });

          if (props.onRefresh) {
            await props.onRefresh();
          }
        } catch (error) {
          console.error("Failed to import PDF:", error);
          throw error;
        }
      }
    }
  } catch (error) {
    console.error("Failed to select PDF:", error);
  }
}
</script>

<template>
  <!-- Toolbar -->
  <div class="document-toolbar">
    <div class="toolbar-actions">
      <v-btn
        size="small"
        variant="tonal"
        prepend-icon="mdi-file-pdf-box"
        @click="handlePdfImport"
      >
        {{ t("toolbar.importPdf") }}
      </v-btn>
      <v-btn
        size="small"
        variant="tonal"
        prepend-icon="mdi-identifier"
        @click="handleDoiButtonClick"
      >
        {{ t("toolbar.doi") }}
      </v-btn>
      <v-btn
        size="small"
        variant="tonal"
        prepend-icon="mdi-file-document-outline"
        @click="handleArxivButtonClick"
      >
        {{ t("toolbar.arxiv") }}
      </v-btn>
    </div>
  </div>

  <!-- DOI Import Dialog -->
  <v-dialog
    v-model="doiDialogOpen"
    max-width="480"
    @click:outside="handleDoiDialogClose"
  >
    <v-card>
      <v-card-title>{{ t("toolbar.importByDoi") }}</v-card-title>
      <v-card-text>
        <div class="dialog-description">{{ t("toolbar.doiDescription") }}</div>
        <v-text-field
          v-model="doiInput"
          :label="t('toolbar.doiPlaceholder')"
          :placeholder="t('toolbar.doiPlaceholder')"
          :error-messages="doiError"
          autofocus
          variant="outlined"
          density="compact"
          :disabled="doiLoading"
          @keyup.enter="handleDoiSubmit"
        />
      </v-card-text>
      <v-card-actions>
        <v-spacer />
        <v-btn @click="handleDoiDialogClose" :disabled="doiLoading">
          {{ t("dialog.cancel") }}
        </v-btn>
        <v-btn
          color="primary"
          variant="tonal"
          @click="handleDoiSubmit"
          :loading="doiLoading"
          :disabled="!doiInput.trim()"
        >
          {{ t("toolbar.import") }}
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>

  <!-- arXiv Import Dialog -->
  <v-dialog
    v-model="arxivDialogOpen"
    max-width="480"
    @click:outside="handleArxivDialogClose"
  >
    <v-card>
      <v-card-title>{{ t("toolbar.importByArxiv") }}</v-card-title>
      <v-card-text>
        <div class="dialog-description">
          {{ t("toolbar.arxivDescription") }}
        </div>
        <v-text-field
          v-model="arxivInput"
          :label="t('toolbar.arxivPlaceholder')"
          :placeholder="t('toolbar.arxivPlaceholder')"
          :error-messages="arxivError"
          autofocus
          variant="outlined"
          density="compact"
          :disabled="arxivLoading"
          @keyup.enter="handleArxivSubmit"
        />
      </v-card-text>
      <v-card-actions>
        <v-spacer />
        <v-btn @click="handleArxivDialogClose" :disabled="arxivLoading">
          {{ t("dialog.cancel") }}
        </v-btn>
        <v-btn
          color="primary"
          variant="tonal"
          @click="handleArxivSubmit"
          :loading="arxivLoading"
          :disabled="!arxivInput.trim()"
        >
          {{ t("toolbar.import") }}
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<style scoped>
.document-toolbar {
  border-bottom: 1px solid var(--vxe-table-border-color);
  min-height: 48px;
  padding: 8px 12px;
  background-color: var(--vxe-table-body-background-color);
  display: flex;
  align-items: center;
  flex-shrink: 0;
}

.toolbar-actions {
  display: flex;
  gap: 8px;
  align-items: center;
}

.dialog-description {
  margin-bottom: 16px;
  color: rgba(var(--v-theme-on-surface), 0.7);
  font-size: 14px;
  line-height: 1.5;
}
</style>

// src/components/document/DocumentToolbar.tsx
import { useState } from "react";
import { Button, Space, Modal, Input, message } from "antd";
import { FilePdfOutlined } from "@ant-design/icons";
import { open } from "@tauri-apps/plugin-dialog";
import { useI18n } from "../../lib/i18n";

// Lazy load invoke helper - works in both Tauri and browser
async function invokeCommand<T = unknown>(
  cmd: string,
  args?: Record<string, unknown>,
): Promise<T> {
  const { invoke } = await import("@tauri-apps/api/core");
  return invoke<T>(cmd, args);
}

interface DocumentToolbarProps {
  onRefresh?: () => void;
  selectedCategoryId?: string | null;
}

export default function DocumentToolbar({
  onRefresh,
  selectedCategoryId,
}: DocumentToolbarProps) {
  const { t } = useI18n();
  const [doiDialogOpen, setDoiDialogOpen] = useState(false);
  const [doiInput, setDoiInput] = useState("");
  const [arxivDialogOpen, setArxivDialogOpen] = useState(false);
  const [arxivInput, setArxivInput] = useState("");

  const handleDoiButtonClick = () => {
    setDoiDialogOpen(true);
    setDoiInput("");
  };

  const handleDoiDialogClose = () => {
    setDoiDialogOpen(false);
    setDoiInput("");
  };

  const handleArxivButtonClick = () => {
    setArxivDialogOpen(true);
    setArxivInput("");
  };

  const handleArxivDialogClose = () => {
    setArxivDialogOpen(false);
    setArxivInput("");
  };

  const handlePdfImport = async () => {
    try {
      const selected = await open({
        multiple: false,
        directory: false,
        filters: [{ name: "PDF", extensions: ["pdf"] }],
      });

      if (selected) {
        const filePath = Array.isArray(selected) ? selected[0] : selected;
        if (filePath) {
          const hide = message.loading("Processing with GROBID...", 0);
          try {
            await invokeCommand("import_paper_by_pdf", {
              filePath: filePath,
              categoryPath: selectedCategoryId,
            });
            hide();
            message.success("Paper imported successfully");
            if (onRefresh) {
              await onRefresh();
            }
          } catch (error) {
            hide();
            console.error("Failed to import PDF:", error);
            message.error(`Import failed: ${String(error)}`);
          }
        }
      }
    } catch (error) {
      console.error("Failed to select PDF:", error);
    }
  };

  const handleArxivSubmit = async () => {
    if (!arxivInput.trim()) {
      return;
    }
    try {
      // Import paper by arXiv ID
      console.info("Importing paper with arXiv ID:", arxivInput.trim());
      await invokeCommand("import_paper_by_arxiv_id", {
        arxivId: arxivInput.trim(),
        categoryPath: selectedCategoryId,
      });

      // Refresh the document list
      if (onRefresh) {
        await onRefresh();
      }

      handleArxivDialogClose();
    } catch (error) {
      console.error("Failed to import paper by arXiv ID:", error);
    }
  };

  const handleDoiSubmit = async () => {
    if (!doiInput.trim()) {
      return;
    }
    try {
      // Import paper by DOI
      console.info("Importing paper with DOI:", doiInput.trim());
      await invokeCommand("import_paper_by_doi", {
        doi: doiInput.trim(),
        categoryPath: selectedCategoryId,
      });

      // Refresh the document list
      if (onRefresh) {
        await onRefresh();
      }

      handleDoiDialogClose();
    } catch (error) {
      console.error("Failed to import paper by DOI:", error);
    }
  };

  return (
    <>
      {/* Toolbar */}
      <div
        style={{
          borderBottom: "1px solid var(--ant-color-border)",
          minHeight: 48,
          padding: "8px 16px",
          backgroundColor: "var(--ant-color-bg-container)",
        }}
      >
        <Space size="small">
          <Button
            size="small"
            icon={<FilePdfOutlined />}
            onClick={handlePdfImport}
          >
            Import PDF
          </Button>
          <Button size="small" onClick={handleDoiButtonClick}>
            {t("toolbar.doi")}
          </Button>
          <Button size="small" onClick={handleArxivButtonClick}>
            {t("toolbar.arxiv")}
          </Button>
        </Space>
      </div>

      {/* DOI Import Dialog */}
      <Modal
        open={doiDialogOpen}
        onCancel={handleDoiDialogClose}
        title={t("toolbar.importByDoi")}
        width={480}
        footer={
          <>
            <Button onClick={handleDoiDialogClose}>{t("dialog.cancel")}</Button>
            <Button type="primary" onClick={handleDoiSubmit}>
              {t("toolbar.import")}
            </Button>
          </>
        }
      >
        <div style={{ marginTop: 16 }}>
          <div style={{ marginBottom: 16, display: "block" }}>
            {t("toolbar.doiDescription")}
          </div>
          <Input
            autoFocus
            placeholder={t("toolbar.doiPlaceholder")}
            value={doiInput}
            onChange={(e) => setDoiInput(e.target.value)}
            onPressEnter={handleDoiSubmit}
          />
        </div>
      </Modal>

      {/* arXiv Import Dialog */}
      <Modal
        open={arxivDialogOpen}
        onCancel={handleArxivDialogClose}
        title={t("toolbar.importByArxiv")}
        width={480}
        footer={
          <>
            <Button onClick={handleArxivDialogClose}>
              {t("dialog.cancel")}
            </Button>
            <Button type="primary" onClick={handleArxivSubmit}>
              {t("toolbar.import")}
            </Button>
          </>
        }
      >
        <div style={{ marginTop: 16 }}>
          <div style={{ marginBottom: 16, display: "block" }}>
            {t("toolbar.arxivDescription")}
          </div>
          <Input
            autoFocus
            placeholder={t("toolbar.arxivPlaceholder")}
            value={arxivInput}
            onChange={(e) => setArxivInput(e.target.value)}
            onPressEnter={handleArxivSubmit}
          />
        </div>
      </Modal>
    </>
  );
}
