// src/lib/components/StatusBar.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte";
  import { t } from "$lib/i18n";

  // Status bar states - using Svelte 5 runes
  let currentTime = $state(new Date());
  let documentCount = $state(0);
  let syncStatus = $state("Synced");
  let isSyncing = $state(false);
  let searchStatus = $state("Ready");
  let memoryUsage = $state("0 MB");

  // Update time and memory usage every second
  let intervalId: ReturnType<typeof setInterval>;

  // Initialize timer on mount
  onMount(() => {
    intervalId = setInterval(() => {
      currentTime = new Date();
      // Simulate memory usage (in actual projects, use performance.memory or Tauri API)
      const memory = Math.floor(Math.random() * 100 + 50);
      memoryUsage = `${memory} MB`;
    }, 1000);
  });

  // Cleanup on unmount
  onDestroy(() => {
    clearInterval(intervalId);
  });

  // Handle sync button click
  function handleSync() {
    isSyncing = true;
    syncStatus = "Syncing...";
    setTimeout(() => {
      isSyncing = false;
      syncStatus = "Synced";
    }, 2000);
  }
</script>

<footer
  class="h-8 bg-gray-800 dark:bg-gray-950 border-t border-gray-700 dark:border-gray-800 flex items-center justify-between px-2 text-xs text-gray-300 dark:text-gray-400 select-none"
>
  <div class="flex items-center gap-2">
    <button
      class="flex items-center gap-1 hover:text-white transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
      class:animate-pulse={isSyncing}
      disabled={isSyncing}
      onclick={handleSync}
    >
      <span
        class="w-1.5 h-1.5 rounded-full"
        class:bg-green-500={syncStatus === "Synced"}
        class:bg-yellow-500={syncStatus === "Syncing..."}
        class:bg-gray-500={syncStatus === "Unsynced"}
      ></span>
      {syncStatus}
    </button>
    <span class="flex items-center gap-0.5">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class="w-2.5 h-2.5"
        viewBox="0 0 20 20"
        fill="currentColor"
      >
        <path
          d="M9 4.804A7.968 7.968 0 005.5 4c-1.255 0-2.443.29-3.5.804v10A7.969 7.969 0 015.5 14c1.669 0 3.218.51 4.5 1.385A7.962 7.962 0 0114.5 14c1.255 0 2.443.29 3.5.804v-10A7.968 7.968 0 0014.5 4c-1.255 0-2.443.29-3.5.804V12a1 1 0 11-2 0V4.804z"
        />
      </svg>
      {$t("status.documents")}: {documentCount}
    </span>
    <span class="hidden md:flex items-center gap-0.5">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class="w-2.5 h-2.5"
        viewBox="0 0 20 20"
        fill="currentColor"
      >
        <path
          fill-rule="evenodd"
          d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
          clip-rule="evenodd"
        />
      </svg>
      {searchStatus}
    </span>
    <span class="hidden lg:flex items-center gap-0.5">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class="w-2.5 h-2.5"
        viewBox="0 0 20 20"
        fill="currentColor"
      >
        <path
          fill-rule="evenodd"
          d="M11.3 1.046A1 1 0 0112 2v5h4a1 1 0 01.82 1.573l-7 10A1 1 0 018 18v-5H4a1 1 0 01-.82-1.573l7-10a1 1 0 011.12-.38z"
          clip-rule="evenodd"
        />
      </svg>
      {memoryUsage}
    </span>
  </div>
  <div class="flex items-center gap-2">
    <span class="hidden sm:inline">{$t("status.version")} 0.1.0</span>
    <span
      class="font-mono bg-gray-700 dark:bg-gray-900 px-1.5 py-0.5 rounded text-[10px]"
    >
      {currentTime.toLocaleTimeString()}
    </span>
  </div>
</footer>

// src/components/StatusBar.tsx
import { useState, useEffect } from "react";
import { Box, Typography, IconButton, Chip } from "@mui/material";
import { Sync, Description, Search, Memory } from "@mui/icons-material";
import { useI18n } from "../lib/i18n";
import ThemeSwitcher from "./ThemeSwitcher";

export default function StatusBar() {
  const { t } = useI18n();
  const [currentTime, setCurrentTime] = useState(new Date());
  const [syncStatus, setSyncStatus] = useState<
    "synced" | "syncing" | "unsynced"
  >("synced");
  const [isSyncing, setIsSyncing] = useState(false);
  const [memoryUsage, setMemoryUsage] = useState("0 MB");
  const documentCount = 0; // TODO: Load from backend

  // Update time and memory usage every second
  useEffect(() => {
    const intervalId = setInterval(() => {
      setCurrentTime(new Date());
      // Simulate memory usage (in actual projects, use performance.memory or Tauri API)
      const memory = Math.floor(Math.random() * 100 + 50);
      setMemoryUsage(`${memory} MB`);
    }, 1000);

    return () => clearInterval(intervalId);
  }, []);

  // Handle sync button click
  const handleSync = () => {
    setIsSyncing(true);
    setSyncStatus("syncing");
    setTimeout(() => {
      setIsSyncing(false);
      setSyncStatus("synced");
    }, 2000);
  };

  return (
    <Box
      sx={{
        height: 32,
        bgcolor: "background.paper",
        borderTop: 1,
        borderColor: "divider",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        px: 1.5,
        userSelect: "none",
      }}
    >
      {/* Left section */}
      <Box sx={{ display: "flex", alignItems: "center", gap: 1.5 }}>
        {/* Sync status */}
        <Box sx={{ display: "flex", alignItems: "center", gap: 0.3 }}>
          <IconButton
            size="small"
            onClick={handleSync}
            disabled={isSyncing}
            sx={{
              p: 0.25,
              color: "text.secondary",
              "&:hover": { color: "text.primary" },
              animation: isSyncing ? "pulse 1s infinite" : "none",
              "@keyframes pulse": {
                "0%": { opacity: 1 },
                "50%": { opacity: 0.5 },
                "100%": { opacity: 1 },
              },
            }}
          >
            <Sync sx={{ fontSize: "18px" }} />
          </IconButton>
          <Chip
            size="small"
            label={t(`status.${syncStatus}`)}
            color={
              syncStatus === "synced"
                ? "success"
                : syncStatus === "syncing"
                  ? "warning"
                  : "default"
            }
            sx={{ height: 24 }}
          />
        </Box>

        {/* Document count */}
        <Box sx={{ display: "flex", alignItems: "center", gap: 0.3 }}>
          <Description sx={{ fontSize: "18px" }} />
          <Typography variant="caption" sx={{ fontSize: "12px" }}>
            {t("status.documents")}: {documentCount}
          </Typography>
        </Box>

        {/* Search status */}
        <Box
          sx={{
            display: { xs: "none", md: "flex" },
            alignItems: "center",
            gap: 0.3,
          }}
        >
          <Search sx={{ fontSize: "18px" }} />
          <Typography variant="caption" sx={{ fontSize: "12px" }}>
            {t("status.searchStatus")}
          </Typography>
        </Box>

        {/* Memory usage */}
        <Box
          sx={{
            display: { xs: "none", lg: "flex" },
            alignItems: "center",
            gap: 0.3,
          }}
        >
          <Memory sx={{ fontSize: "18px" }} />
          <Typography variant="caption" sx={{ fontSize: "12px" }}>
            {memoryUsage}
          </Typography>
        </Box>
      </Box>

      {/* Right section */}
      <Box sx={{ display: "flex", alignItems: "center", gap: 1.5 }}>
        {/* Theme Switcher (Dark Mode, Language, Theme, Accent Color) */}
        <ThemeSwitcher />

        {/* Version */}
        <Typography
          variant="caption"
          sx={{ display: { xs: "none", sm: "block" }, fontSize: "12px" }}
        >
          {t("status.version")} 0.1.0
        </Typography>

        {/* Clock */}
        <Box
          sx={{
            fontFamily: "monospace",
            bgcolor: "action.disabledBackground",
            px: 0.75,
            py: 0.25,
            borderRadius: 0.5,
          }}
        >
          <Typography variant="caption" sx={{ fontSize: "12px" }}>
            {currentTime.toLocaleTimeString()}
          </Typography>
        </Box>
      </Box>
    </Box>
  );
}
