// src/components/AddTagDialog.tsx
import { useState, useEffect } from "react";
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  Button,
  IconButton,
  Typography,
  Box,
} from "@mui/material";
import { Close, Check } from "@mui/icons-material";
import { useI18n } from "../lib/i18n";

// Lazy load invoke helper - works in both Tauri and browser
async function invokeCommand<T = unknown>(
  cmd: string,
  args?: Record<string, unknown>,
): Promise<T> {
  const { invoke } = await import("@tauri-apps/api/core");
  return invoke<T>(cmd, args);
}

// Predefined color palette (must match backend and TagsSection)
const TAG_COLORS: Record<string, string> = {
  red: "#ef4444",
  orange: "#f97316",
  amber: "#f59e0b",
  yellow: "#eab308",
  lime: "#84cc16",
  green: "#22c55e",
  emerald: "#10b981",
  teal: "#14b8a6",
  cyan: "#06b6d4",
  sky: "#0ea5e9",
  blue: "#3b82f6",
  indigo: "#6366f1",
  violet: "#8b5cf6",
  purple: "#a855f7",
  fuchsia: "#d946ef",
  pink: "#ec4899",
  rose: "#f43f5e",
};

interface AddTagDialogProps {
  open: boolean;
  onClose: () => void;
  onTagCreated: () => void;
}

export default function AddTagDialog({
  open,
  onClose,
  onTagCreated,
}: AddTagDialogProps) {
  const { t } = useI18n();
  const [name, setName] = useState("");
  const [selectedColor, setSelectedColor] = useState("blue");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  // Reset form when dialog opens
  useEffect(() => {
    if (open) {
      setName("");
      setSelectedColor("blue");
      setError("");
    }
  }, [open]);

  const handleSubmit = async () => {
    if (!name.trim()) {
      setError(t("dialog.tagNameRequired"));
      return;
    }

    if (name.length > 30) {
      setError(t("dialog.tagNameMaxLength"));
      return;
    }

    setLoading(true);
    try {
      await invokeCommand("create_label", {
        name: name.trim(),
        color: selectedColor,
      });
      setName("");
      setSelectedColor("blue");
      setError("");
      onTagCreated();
      onClose();
    } catch (err) {
      setError(err as string);
    } finally {
      setLoading(false);
    }
  };

  const handleClose = () => {
    setName("");
    setSelectedColor("blue");
    setError("");
    onClose();
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !loading && name.trim() && name.length <= 30) {
      handleSubmit();
    }
  };

  return (
    <Dialog open={open} onClose={handleClose} maxWidth="sm" fullWidth>
      <DialogTitle>
        <Typography variant="h6" component="div">
          {t("dialog.addTag")}
        </Typography>
        <IconButton
          aria-label="close"
          onClick={handleClose}
          sx={{
            position: "absolute",
            right: 8,
            top: 8,
            color: "grey.500",
          }}
        >
          <Close />
        </IconButton>
      </DialogTitle>
      <DialogContent dividers>
        {/* Tag name input */}
        <TextField
          autoFocus
          margin="dense"
          label={t("dialog.tagName")}
          fullWidth
          variant="outlined"
          value={name}
          onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
            setName(e.target.value);
            setError("");
          }}
          onKeyPress={handleKeyPress}
          error={!!error}
          helperText={error}
          disabled={loading}
          sx={{ mt: 2 }}
          placeholder={t("dialog.enterTagName")}
        />

        {/* Color picker */}
        <Box sx={{ mt: 3 }}>
          <Typography
            variant="caption"
            component="legend"
            sx={{ mb: 1.5, display: "block", fontWeight: 500 }}
          >
            {t("dialog.selectColor")}
          </Typography>
          <Box
            sx={{
              display: "flex",
              flexWrap: "wrap",
              gap: 1,
            }}
          >
            {Object.entries(TAG_COLORS).map(([colorName, colorHex]) => (
              <Box
                key={colorName}
                onClick={() => setSelectedColor(colorName)}
                sx={{
                  width: 32,
                  height: 32,
                  borderRadius: "50%",
                  bgcolor: colorHex,
                  border: 2,
                  borderColor:
                    selectedColor === colorName
                      ? "text.primary"
                      : "transparent",
                  cursor: "pointer",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  transition: "all 0.2s",
                  "&:hover": {
                    transform: "scale(1.1)",
                  },
                }}
                title={colorName}
              >
                {selectedColor === colorName && (
                  <Check
                    sx={{
                      color: "white",
                      fontSize: 20,
                      filter: "drop-shadow(0 1px 2px rgba(0,0,0,0.3))",
                    }}
                  />
                )}
              </Box>
            ))}
          </Box>
        </Box>

        <Typography
          variant="caption"
          color="text.secondary"
          sx={{ mt: 2, display: "block" }}
        >
          {t("dialog.tagNameRules")}
        </Typography>
      </DialogContent>
      <DialogActions>
        <Button onClick={handleClose} disabled={loading}>
          {t("dialog.cancel")}
        </Button>
        <Button
          onClick={handleSubmit}
          variant="contained"
          disabled={loading || !name.trim() || name.length > 30}
        >
          {loading ? t("dialog.adding") : t("dialog.add")}
        </Button>
      </DialogActions>
    </Dialog>
  );
}

// src/components/dialogs/AddTagDialog.vue
<script setup lang="ts">
import { ref, watch, computed } from "vue";
import { invokeCommand } from "@/lib/tauri";
import { useI18n } from "@/lib/i18n";

const { t } = useI18n();

interface Props {
  modelValue: boolean;
  tagId?: number;
  tagName?: string;
  tagColor?: string;
}

const props = defineProps<Props>();

const emit = defineEmits<{
  "update:modelValue": [value: boolean];
  tagCreated: [];
}>();

// Available colors for labels
const labelColors = [
  { value: "red", color: "#ef4444" },
  { value: "orange", color: "#f97316" },
  { value: "amber", color: "#f59e0b" },
  { value: "yellow", color: "#eab308" },
  { value: "lime", color: "#84cc16" },
  { value: "green", color: "#22c55e" },
  { value: "emerald", color: "#10b981" },
  { value: "teal", color: "#14b8a6" },
  { value: "cyan", color: "#06b6d4" },
  { value: "sky", color: "#0ea5e9" },
  { value: "blue", color: "#3b82f6" },
  { value: "indigo", color: "#6366f1" },
  { value: "violet", color: "#8b5cf6" },
  { value: "purple", color: "#a855f7" },
  { value: "fuchsia", color: "#d946ef" },
  { value: "pink", color: "#ec4899" },
  { value: "rose", color: "#f43f5e" },
];

// State
const name = ref("");
const selectedColor = ref("blue");
const error = ref("");
const loading = ref(false);

// Check if editing mode
const isEditMode = computed(() => !!props.tagId);

// Dialog title
const dialogTitle = computed(() =>
  isEditMode.value ? t("dialog.editTag") : t("dialog.addTag"),
);

// Reset form when dialog opens
watch(
  () => props.modelValue,
  (isOpen) => {
    if (isOpen) {
      if (isEditMode.value) {
        name.value = props.tagName || "";
        selectedColor.value = props.tagColor || "blue";
      } else {
        name.value = "";
        selectedColor.value = "blue";
      }
      error.value = "";
    }
  },
);

// Close dialog
function handleClose() {
  name.value = "";
  selectedColor.value = "blue";
  error.value = "";
  emit("update:modelValue", false);
}

// Submit form
async function handleSubmit() {
  if (!name.value.trim()) {
    error.value = t("dialog.tagNameRequired");
    return;
  }

  if (name.value.length > 30) {
    error.value = t("dialog.tagNameMaxLength");
    return;
  }

  loading.value = true;
  try {
    if (isEditMode.value && props.tagId) {
      // Update existing tag
      await invokeCommand("update_label", {
        id: props.tagId,
        name: name.value.trim(),
        color: selectedColor.value,
      });
      console.info("Label updated successfully:", name.value.trim());
    } else {
      // Create new tag
      await invokeCommand("create_label", {
        name: name.value.trim(),
        color: selectedColor.value,
      });
      console.info("Label created successfully:", name.value.trim());
    }

    name.value = "";
    selectedColor.value = "blue";
    error.value = "";
    emit("tagCreated");
    emit("update:modelValue", false);
  } catch (err) {
    error.value = err as string;
  } finally {
    loading.value = false;
  }
}

// Handle Enter key
function handleKeyPress(event: KeyboardEvent) {
  if (
    event.key === "Enter" &&
    !loading.value &&
    name.value.trim() &&
    name.value.length <= 30
  ) {
    handleSubmit();
  }
}
</script>

<template>
  <v-dialog
    :model-value="modelValue"
    @update:model-value="emit('update:modelValue', $event)"
    max-width="480"
  >
    <v-card>
      <v-card-title>
        <v-icon start>mdi-label</v-icon>
        {{ dialogTitle }}
      </v-card-title>

      <v-card-text>
        <v-alert v-if="error" type="error" :text="error" class="mb-4" />

        <v-text-field
          v-model="name"
          autofocus
          :label="t('dialog.enterTagName')"
          variant="outlined"
          :error-messages="error ? [error] : []"
          :disabled="loading"
          @keyup="handleKeyPress"
        />

        <div class="mt-4">
          <div class="text-caption text-grey mb-2">
            {{ t("dialog.selectColor") }}
          </div>
          <div class="color-selector">
            <div
              v-for="colorOption in labelColors"
              :key="colorOption.value"
              class="color-option"
              :class="{ selected: selectedColor === colorOption.value }"
              :style="{ backgroundColor: colorOption.color }"
              @click="selectedColor = colorOption.value"
            >
              <v-icon
                v-if="selectedColor === colorOption.value"
                color="white"
                size="small"
              >
                mdi-check
              </v-icon>
            </div>
          </div>
        </div>
      </v-card-text>

      <v-card-actions>
        <v-spacer />
        <v-btn @click="handleClose" :disabled="loading">
          {{ t("dialog.cancel") }}
        </v-btn>
        <v-btn
          color="primary"
          @click="handleSubmit"
          :loading="loading"
          :disabled="!name.trim() || name.length > 30"
        >
          {{ t("dialog.save") }}
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<style scoped>
.color-selector {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.color-option {
  width: 36px;
  height: 36px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  border: 2px solid transparent;
  transition: all 0.2s;
}

.color-option:hover {
  transform: scale(1.1);
}

.color-option.selected {
  border-color: rgb(var(--v-theme-primary));
  box-shadow: 0 0 8px rgba(var(--v-theme-primary), 0.5);
}
</style>
