// src/lib/components/AddTagDialog.svelte
<script lang="ts">
  import { invoke } from "@tauri-apps/api/core";
  import { X } from "lucide-svelte";

  // Props using Svelte 5 runes
  interface Props {
    open: boolean;
    onTagCreated?: () => void;
    onClose?: () => void;
  }

  let { open, onTagCreated, onClose }: Props = $props();

  // Predefined color palette (must match TagsSection)
  const TAG_COLORS: Record<string, string> = {
    red: "#ef4444",
    orange: "#f97316",
    amber: "#f59e0b",
    yellow: "#eab308",
    lime: "#84cc16",
    green: "#22c55e",
    emerald: "#10b981",
    teal: "#14b8a6",
    cyan: "#06b6d4",
    sky: "#0ea5e9",
    blue: "#3b82f6",
    indigo: "#6366f1",
    violet: "#8b5cf6",
    purple: "#a855f7",
    fuchsia: "#d946ef",
    pink: "#ec4899",
    rose: "#f43f5e",
  };

  // Form state
  let tagName = $state("");
  let selectedColor = $state("blue"); // Default color

  // Error state
  let errorMessage = $state("");

  // Reset form
  function resetForm() {
    tagName = "";
    selectedColor = "blue";
    errorMessage = "";
  }

  // Close dialog
  function closeDialog() {
    resetForm();
    if (onClose) {
      onClose();
    }
  }

  // Create tag
  async function handleCreateTag() {
    // Validate
    if (!tagName.trim()) {
      errorMessage = "请输入标签名称";
      return;
    }

    if (tagName.trim().length > 50) {
      errorMessage = "标签名称不能超过50个字符";
      return;
    }

    try {
      await invoke("create_label", {
        name: tagName.trim(),
        color: selectedColor,
      });

      // Reset and close
      resetForm();
      if (onClose) {
        onClose();
      }

      // Notify parent to refresh tags
      if (onTagCreated) {
        onTagCreated();
      }
    } catch (error) {
      console.error("Failed to create tag:", error);
      errorMessage = `创建标签失败: ${error}`;
    }
  }

  // Handle keyboard shortcuts
  function handleKeydown(event: KeyboardEvent) {
    if (event.key === "Escape") {
      closeDialog();
    } else if (event.key === "Enter" && (event.metaKey || event.ctrlKey)) {
      handleCreateTag();
    }
  }
</script>

{#if open}
  <div
    class="fixed inset-0 z-50 flex items-center justify-center bg-black/50"
    onmousedown={(e) => {
      if (e.target === e.currentTarget) closeDialog();
    }}
  >
    <div
      class="bg-white dark:bg-gray-800 rounded-lg shadow-xl w-96 max-w-[90vw]"
      onkeydown={handleKeydown}
      role="dialog"
      aria-modal="true"
    >
      <!-- Header -->
      <div
        class="flex items-center justify-between p-4 border-b border-gray-200 dark:border-gray-700"
      >
        <h2 class="text-lg font-semibold text-gray-900 dark:text-gray-100">
          添加标签
        </h2>
        <button
          onclick={closeDialog}
          class="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 transition-colors"
          aria-label="关闭"
        >
          <X size={20} />
        </button>
      </div>

      <!-- Body -->
      <div class="p-4 space-y-4">
        <!-- Error message -->
        {#if errorMessage}
          <div
            class="p-3 text-sm text-red-600 bg-red-50 dark:bg-red-900/20 dark:text-red-400 rounded-md"
          >
            {errorMessage}
          </div>
        {/if}

        <!-- Tag name input -->
        <div>
          <label
            for="tag-name"
            class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
          >
            标签名称
          </label>
          <input
            id="tag-name"
            type="text"
            bind:value={tagName}
            placeholder="输入标签名称..."
            class="w-full px-3 py-2 text-sm border border-gray-300 dark:border-gray-600 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-gray-700 dark:text-white"
            autofocus
          />
        </div>

        <!-- Color picker -->
        <div>
          <label
            class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2"
          >
            选择颜色
          </label>
          <div class="flex flex-wrap gap-2">
            {#each Object.entries(TAG_COLORS) as [colorName, colorHex]}
              <button
                type="button"
                class="w-8 h-8 rounded-full border-2 transition-all hover:scale-110 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                class:border-gray-300={selectedColor !== colorName}
                class:border-gray-900={selectedColor === colorName}
                style="background-color: {colorHex};"
                onclick={() => (selectedColor = colorName)}
                aria-label="选择 {colorName} 颜色"
                title={colorName}
              >
                {#if selectedColor === colorName}
                  <svg
                    class="w-5 h-5 text-white drop-shadow-md"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="3"
                      d="M5 13l4 4L19 7"
                    />
                  </svg>
                {/if}
              </button>
            {/each}
          </div>
        </div>
      </div>

      <!-- Footer -->
      <div
        class="flex justify-end gap-2 p-4 border-t border-gray-200 dark:border-gray-700"
      >
        <button
          onclick={closeDialog}
          class="px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md hover:bg-gray-50 dark:hover:bg-gray-600 transition-colors"
        >
          取消
        </button>
        <button
          onclick={handleCreateTag}
          class="px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-md hover:bg-blue-700 transition-colors"
        >
          创建
        </button>
      </div>
    </div>
  </div>
{/if}

// src/components/dialogs/AddTagDialog.tsx
import { useState, useEffect } from "react";
import { Modal, Input, Button, Typography } from "antd";
import { CloseOutlined, CheckOutlined } from "@ant-design/icons";
import { useI18n } from "../../lib/i18n";

// Lazy load invoke helper - works in both Tauri and browser
async function invokeCommand<T = unknown>(
  cmd: string,
  args?: Record<string, unknown>,
): Promise<T> {
  const { invoke } = await import("@tauri-apps/api/core");
  return invoke<T>(cmd, args);
}

// Predefined color palette (must match backend and TagsSection)
const TAG_COLORS: Record<string, string> = {
  red: "#ef4444",
  orange: "#f97316",
  amber: "#f59e0b",
  yellow: "#eab308",
  lime: "#84cc16",
  green: "#22c55e",
  emerald: "#10b981",
  teal: "#14b8a6",
  cyan: "#06b6d4",
  sky: "#0ea5e9",
  blue: "#3b82f6",
  indigo: "#6366f1",
  violet: "#8b5cf6",
  purple: "#a855f7",
  fuchsia: "#d946ef",
  pink: "#ec4899",
  rose: "#f43f5e",
};

interface AddTagDialogProps {
  open: boolean;
  onClose: () => void;
  onTagCreated: () => void;
}

export default function AddTagDialog({
  open,
  onClose,
  onTagCreated,
}: AddTagDialogProps) {
  const { t } = useI18n();
  const [name, setName] = useState("");
  const [selectedColor, setSelectedColor] = useState("blue");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  // Reset form when dialog opens
  useEffect(() => {
    if (open) {
      setName("");
      setSelectedColor("blue");
      setError("");
    }
  }, [open]);

  const handleSubmit = async () => {
    if (!name.trim()) {
      setError(t("dialog.tagNameRequired"));
      return;
    }

    if (name.length > 30) {
      setError(t("dialog.tagNameMaxLength"));
      return;
    }

    setLoading(true);
    try {
      await invokeCommand("create_label", {
        name: name.trim(),
        color: selectedColor,
      });
      console.info("Tag created successfully:", name.trim());
      setName("");
      setSelectedColor("blue");
      setError("");
      onTagCreated();
      onClose();
    } catch (err) {
      console.error("Failed to create tag:", err);
      const errorMessage =
        err instanceof Error
          ? err.message
          : typeof err === "object" && err !== null
            ? (err as any).message || String(err)
            : String(err);
      setError(errorMessage);
    } finally {
      setLoading(false);
    }
  };

  const handleClose = () => {
    setName("");
    setSelectedColor("blue");
    setError("");
    onClose();
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !loading && name.trim() && name.length <= 30) {
      handleSubmit();
    }
  };

  return (
    <Modal
      open={open}
      onCancel={handleClose}
      title={
        <div style={{ position: "relative", paddingRight: 32 }}>
          <Typography.Text strong>{t("dialog.addTag")}</Typography.Text>
        </div>
      }
      closeIcon={<CloseOutlined />}
      width={480}
      footer={
        <>
          <Button onClick={handleClose} disabled={loading}>
            {t("dialog.cancel")}
          </Button>
          <Button
            type="primary"
            onClick={handleSubmit}
            loading={loading}
            disabled={!name.trim() || name.length > 30}
          >
            {t("dialog.add")}
          </Button>
        </>
      }
    >
      {/* Tag name input */}
      <div style={{ marginBottom: 16 }}>
        <Input
          autoFocus
          placeholder={t("dialog.enterTagName")}
          value={name}
          onChange={(e) => {
            setName(e.target.value);
            setError("");
          }}
          onPressEnter={handleKeyPress}
          status={error ? "error" : ""}
          disabled={loading}
        />
        {error && (
          <Typography.Text type="danger" style={{ fontSize: 12 }}>
            {error}
          </Typography.Text>
        )}
      </div>

      {/* Color picker */}
      <div style={{ marginBottom: 16 }}>
        <Typography.Text strong style={{ marginBottom: 8, display: "block" }}>
          {t("dialog.selectColor")}
        </Typography.Text>
        <div
          style={{
            display: "flex",
            flexWrap: "wrap",
            gap: 8,
          }}
        >
          {Object.entries(TAG_COLORS).map(([colorName, colorHex]) => (
            <div
              key={colorName}
              onClick={() => setSelectedColor(colorName)}
              style={{
                width: 32,
                height: 32,
                borderRadius: "50%",
                backgroundColor: colorHex,
                border:
                  selectedColor === colorName
                    ? "2px solid currentColor"
                    : "2px solid transparent",
                cursor: "pointer",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                transition: "all 0.2s",
              }}
              title={colorName}
            >
              {selectedColor === colorName && (
                <CheckOutlined
                  style={{
                    color: "white",
                    fontSize: 16,
                    filter: "drop-shadow(0 1px 2px rgba(0,0,0,0.3))",
                  }}
                />
              )}
            </div>
          ))}
        </div>
      </div>

      <Typography.Text type="secondary" style={{ fontSize: 12 }}>
        {t("dialog.tagNameRules")}
      </Typography.Text>
    </Modal>
  );
}
