// src/components/TagsSection.tsx
import { useState, useEffect, useCallback } from "react";
import { invoke } from "@tauri-apps/api/core";
import {
  Box,
  Typography,
  Chip,
  IconButton,
  Menu,
  MenuItem,
} from "@mui/material";
import { Delete, MoreVert } from "@mui/icons-material";
import AddTagDialog from "./AddTagDialog";

// Predefined color palette for tags
const TAG_COLORS: Record<string, string> = {
  red: "#ef4444",
  orange: "#f97316",
  amber: "#f59e0b",
  yellow: "#eab308",
  lime: "#84cc16",
  green: "#22c55e",
  emerald: "#10b981",
  teal: "#14b8a6",
  cyan: "#06b6d4",
  sky: "#0ea5e9",
  blue: "#3b82f6",
  indigo: "#6366f1",
  violet: "#8b5cf6",
  purple: "#a855f7",
  fuchsia: "#d946ef",
  pink: "#ec4899",
  rose: "#f43f5e",
};

interface Tag {
  id: number;
  name: string;
  count: number;
  color: string;
}

interface TagsSectionProps {
  onAddTag: () => void;
}

export default function TagsSection({ onAddTag }: TagsSectionProps) {
  const [tags, setTags] = useState<Tag[]>([]);
  const [loading, setLoading] = useState(true);
  const [showAddDialog, setShowAddDialog] = useState(false);
  const [contextMenu, setContextMenu] = useState<{
    anchorEl: null | HTMLElement;
    tag: Tag | null;
  }>({
    anchorEl: null,
    tag: null,
  });

  // Load tags from backend
  const loadTags = useCallback(async () => {
    setLoading(true);
    try {
      const labels = await invoke<Record<string, any>[]>("get_all_labels");

      const processedTags: Tag[] = labels.map((label) => ({
        id: label.id,
        name: label.name,
        count: label.document_count || 0,
        color: TAG_COLORS[label.color] || TAG_COLORS.blue,
      }));

      setTags(processedTags);
    } catch (error) {
      console.error("Failed to load labels:", error);
      // Use demo data as fallback
      setTags([
        { id: 1, name: "AI", count: 12, color: TAG_COLORS.blue },
        { id: 2, name: "Machine Learning", count: 8, color: TAG_COLORS.indigo },
        { id: 3, name: "Deep Learning", count: 6, color: TAG_COLORS.purple },
        { id: 4, name: "NLP", count: 5, color: TAG_COLORS.red },
        { id: 5, name: "Computer Vision", count: 4, color: TAG_COLORS.orange },
      ]);
    } finally {
      setLoading(false);
    }
  }, []);

  // Load on mount
  useEffect(() => {
    loadTags();
  }, [loadTags]);

  // Handle tag created
  const handleTagCreated = async () => {
    setShowAddDialog(false);
    await loadTags();
  };

  // Handle context menu
  const handleContextMenu = (
    event: React.MouseEvent<HTMLElement>,
    tag: Tag,
  ) => {
    event.preventDefault();
    event.stopPropagation();
    setContextMenu({
      anchorEl: event.currentTarget,
      tag,
    });
  };

  // Handle close context menu
  const handleCloseContextMenu = () => {
    setContextMenu({
      anchorEl: null,
      tag: null,
    });
  };

  // Handle delete tag
  const handleDeleteTag = async () => {
    if (!contextMenu.tag) return;

    const tagId = contextMenu.tag.id;
    try {
      await invoke("delete_label", { id: tagId });
      handleCloseContextMenu();
      await loadTags();
    } catch (error) {
      console.error("Failed to delete tag:", error);
      alert(`删除标签失败: ${error}`);
    }
  };

  return (
    <Box sx={{ py: 1 }}>
      {/* Header */}
      <Box
        sx={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          px: 1,
          mb: 1,
        }}
      >
        <Typography variant="caption" color="text.secondary">
          标签（{tags.length}）
        </Typography>
        <IconButton
          size="small"
          onClick={() => setShowAddDialog(true)}
          aria-label="添加标签"
        >
          <MoreVert fontSize="small" />
        </IconButton>
      </Box>

      {/* Tags list */}
      {loading ? (
        <Box sx={{ px: 2, py: 1, textAlign: "center" }}>
          <Typography variant="caption" color="text.secondary">
            加载中...
          </Typography>
        </Box>
      ) : tags.length === 0 ? (
        <Box sx={{ px: 2, py: 1, textAlign: "center" }}>
          <Typography variant="caption" color="text.secondary">
            暂无标签
          </Typography>
        </Box>
      ) : (
        <Box sx={{ display: "flex", flexWrap: "wrap", gap: 0.5, px: 1 }}>
          {tags.map((tag) => (
            <Chip
              key={tag.id}
              label={`${tag.name} (${tag.count})`}
              size="small"
              sx={{
                fontSize: "0.7rem",
                height: 24,
                bgcolor: tag.color,
                color: "white",
                "&:hover": {
                  bgcolor: tag.color,
                  opacity: 0.8,
                },
                cursor: "pointer",
              }}
              onClick={(e) => handleContextMenu(e, tag)}
            />
          ))}
        </Box>
      )}

      {/* Add Tag Dialog */}
      <AddTagDialog
        open={showAddDialog}
        onClose={() => setShowAddDialog(false)}
        onTagCreated={handleTagCreated}
      />

      {/* Context Menu */}
      <Menu
        anchorEl={contextMenu.anchorEl}
        open={Boolean(contextMenu.anchorEl)}
        onClose={handleCloseContextMenu}
      >
        <MenuItem onClick={handleDeleteTag} disabled={!contextMenu.tag}>
          <Delete fontSize="small" sx={{ mr: 1 }} />
          删除标签
        </MenuItem>
      </Menu>
    </Box>
  );
}

// src/lib/components/TagsSection.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { invoke } from "@tauri-apps/api/core";
  import { t } from "$lib/i18n";
  import { Tags, Plus, Trash2 } from "lucide-svelte";
  import AddTagDialog from "./AddTagDialog.svelte";

  // Predefined color palette for tags
  const TAG_COLORS: Record<string, string> = {
    red: "#ef4444",
    orange: "#f97316",
    amber: "#f59e0b",
    yellow: "#eab308",
    lime: "#84cc16",
    green: "#22c55e",
    emerald: "#10b981",
    teal: "#14b8a6",
    cyan: "#06b6d4",
    sky: "#0ea5e9",
    blue: "#3b82f6",
    indigo: "#6366f1",
    violet: "#8b5cf6",
    purple: "#a855f7",
    fuchsia: "#d946ef",
    pink: "#ec4899",
    rose: "#f43f5e",
  };

  // Tags state - using Svelte 5 runes
  let allTags = $state<
    Array<{ id: number; name: string; count: number; color: string }>
  >([]);

  // Dialog state
  let showDialog = $state(false);

  // Context menu state
  let contextMenu = $state<{
    visible: boolean;
    x: number;
    y: number;
    tagId: number | null;
    tagName: string;
  }>({
    visible: false,
    x: 0,
    y: 0,
    tagId: null,
    tagName: "",
  });

  // Close dialog handler
  function closeDialog() {
    showDialog = false;
  }

  // Load labels from backend on mount
  async function loadTags() {
    try {
      console.log("Loading labels from backend...");
      const labels = await invoke<Record<string, any>[]>("get_all_labels");
      console.log("Received labels:", labels);

      allTags = labels.map((label) => ({
        id: label.id,
        name: label.name,
        count: label.document_count || 0,
        // Use the color name from database to get the color code
        color: TAG_COLORS[label.color] || TAG_COLORS["blue"],
      }));

      console.log("Processed tags count:", allTags.length);
    } catch (error) {
      console.error("Failed to load labels:", error);
      // Use demo data as fallback if running in browser (not Tauri)
      console.log("Using demo data as fallback");
      allTags = [
        { id: 1, name: "AI", count: 12, color: TAG_COLORS["blue"] },
        {
          id: 2,
          name: "Machine Learning",
          count: 8,
          color: TAG_COLORS["indigo"],
        },
        { id: 3, name: "Deep Learning", count: 6, color: TAG_COLORS["purple"] },
        { id: 4, name: "NLP", count: 5, color: TAG_COLORS["red"] },
        {
          id: 5,
          name: "Computer Vision",
          count: 4,
          color: TAG_COLORS["orange"],
        },
      ];
    }
  }

  // Load labels from backend on mount
  onMount(() => {
    loadTags();

    // Close context menu on click outside
    const handleClickOutside = () => {
      if (contextMenu.visible) {
        contextMenu.visible = false;
      }
    };

    document.addEventListener("click", handleClickOutside);
    return () => {
      document.removeEventListener("click", handleClickOutside);
    };
  });

  // Handle right-click on tag
  function handleTagContextMenu(
    event: MouseEvent,
    tag: { id: number; name: string },
  ) {
    event.preventDefault();
    event.stopPropagation();

    contextMenu = {
      visible: true,
      x: event.clientX,
      y: event.clientY,
      tagId: tag.id,
      tagName: tag.name,
    };
  }

  // Delete tag
  async function handleDeleteTag() {
    if (contextMenu.tagId === null || contextMenu.tagId === undefined) return;

    const tagId = contextMenu.tagId;
    console.log("Deleting tag with ID:", tagId);

    try {
      console.log("Invoking delete_label command with id:", tagId);
      await invoke("delete_label", { id: tagId });
      console.log("Tag deleted successfully");

      // Close context menu
      contextMenu.visible = false;

      // Reload tags
      await loadTags();
    } catch (error) {
      console.error("Failed to delete tag:", error);
      alert(`删除标签失败: ${error}`);
    }
  }
</script>

<div class="tags-section">
  <h3
    class="text-sm font-semibold text-gray-900 dark:text-gray-100 mb-2 pb-1 border-b border-gray-200 dark:border-gray-700 flex items-center justify-between"
  >
    <div class="flex items-center gap-1">
      <Tags size={14} />
      {$t("navigation.tags")}
    </div>
    <button
      onclick={() => (showDialog = true)}
      class="text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200 transition-colors p-0.5 rounded hover:bg-gray-100 dark:hover:bg-gray-700"
      aria-label="添加标签"
      title="添加标签"
    >
      <Plus size={14} />
    </button>
  </h3>
  <div class="overflow-y-auto pr-1" style="max-height: 200px;">
    <div class="flex flex-wrap gap-1.5">
      {#each allTags as tag}
        <span
          class="inline-flex items-center gap-1 px-2 py-1 text-xs font-medium rounded-full text-white hover:opacity-80 cursor-pointer transition-opacity"
          style="background-color: {tag.color};"
          title="{tag.count} documents"
          oncontextmenu={(e) => handleTagContextMenu(e, tag)}
        >
          {tag.name}
          <span class="text-[10px] opacity-70">({tag.count})</span>
        </span>
      {/each}
    </div>
  </div>
</div>

<!-- Context Menu -->
{#if contextMenu.visible}
  <div
    class="fixed z-50 bg-white dark:bg-gray-800 rounded-lg shadow-lg border border-gray-200 dark:border-gray-700 py-1 min-w-[150px]"
    style="left: {contextMenu.x}px; top: {contextMenu.y}px;"
    onmousedown={(e) => e.stopPropagation()}
  >
    <div
      class="px-3 py-2 text-xs text-gray-500 dark:text-gray-400 border-b border-gray-200 dark:border-gray-700"
    >
      {contextMenu.tagName}
    </div>
    <button
      onclick={handleDeleteTag}
      class="w-full px-3 py-2 text-sm text-left text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20 flex items-center gap-2 transition-colors"
    >
      <Trash2 size={14} />
      删除标签
    </button>
  </div>
{/if}

<!-- Add Tag Dialog -->
<AddTagDialog open={showDialog} onTagCreated={loadTags} onClose={closeDialog} />

<style>
  /* Custom scrollbar for tags section */
  .tags-section .overflow-y-auto::-webkit-scrollbar {
    width: 6px;
  }

  .tags-section .overflow-y-auto::-webkit-scrollbar-track {
    background: transparent;
  }

  .tags-section .overflow-y-auto::-webkit-scrollbar-thumb {
    background: #d1d5db;
    border-radius: 3px;
  }

  .tags-section .overflow-y-auto::-webkit-scrollbar-thumb:hover {
    background: #9ca3af;
  }

  /* Dark mode scrollbar */
  @media (prefers-color-scheme: dark) {
    .tags-section .overflow-y-auto::-webkit-scrollbar-thumb {
      background: #4b5563;
    }

    .tags-section .overflow-y-auto::-webkit-scrollbar-thumb:hover {
      background: #6b7280;
    }
  }

  /* Dark mode specific scrollbar */
  :global(.dark) .tags-section .overflow-y-auto::-webkit-scrollbar-thumb {
    background: #4b5563;
  }

  :global(.dark) .tags-section .overflow-y-auto::-webkit-scrollbar-thumb:hover {
    background: #6b7280;
  }
</style>
